name: Render PNG all type Schedule

on:
  schedule:
    - cron: '6,16,26,36,46,56 * * * *'  # На 06, 16, 26, 36, 46, 56 хвилину кожної години
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: pip install matplotlib numpy
      
      - name: Download JSON data from repository
        run: |
          cp data/Vinnytsiaoblenerho.json Vinnytsiaoblenerho.json
      
      - name: Generate individual schedules
        run: |
          python scripts/render_png.py --json Vinnytsiaoblenerho.json --out .//images/Vinnytsiaoblenerho
    
      - name: Generate all schedules today
        run: |
          python scripts/render_png_all_today.py --json Vinnytsiaoblenerho.json --out ./images/Vinnytsiaoblenerho
      
      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add images/Vinnytsiaoblenerho/
          if git diff --quiet --cached; then
            echo "No changes to commit"
          else
            git commit -m "Update schedules $(date)"
            git push origin main
          fi
